/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GoogleReviewConfig {
  'fallbackRating' : string,
  'placeId' : string,
  'apiKey' : string,
}
export interface MenuCategory { 'name' : string, 'items' : Array<MenuItem> }
export interface MenuItem {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'price' : number,
}
export interface Order {
  'id' : number,
  'customerName' : string,
  'customerAddress' : string,
  'totalAmount' : number,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : number,
  'quantity' : number,
  'price' : number,
}
export interface ProductCategoryResponse {
  'categories' : Array<SwitchCategory>,
  'products' : Array<SwitchProduct>,
}
export interface SwitchCategory { 'id' : number, 'name' : string }
export interface SwitchProduct {
  'id' : number,
  'categoryId' : [] | [number],
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'price' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminSeedMenuItems' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, number, string, string, string],
    number
  >,
  'createSwitchCategory' : ActorMethod<[string], number>,
  'createSwitchProduct' : ActorMethod<
    [string, string, number, string, boolean, [] | [number]],
    number
  >,
  'deleteSwitchCategory' : ActorMethod<[number], undefined>,
  'deleteSwitchProduct' : ActorMethod<[number], undefined>,
  'fetchGoogleRating' : ActorMethod<
    [],
    {
      'fallbackMessage' : string,
      'rating' : [] | [number],
      'reviewCount' : [] | [bigint],
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoogleReviewConfig' : ActorMethod<[], [] | [GoogleReviewConfig]>,
  'getMenu' : ActorMethod<[], Array<MenuCategory>>,
  'getOrderById' : ActorMethod<[number], [] | [Order]>,
  'getSwitchCatalog' : ActorMethod<[], ProductCategoryResponse>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateGoogleReviewConfig' : ActorMethod<[string, string, string], undefined>,
  'updateSwitchCategory' : ActorMethod<[number, string], undefined>,
  'updateSwitchProduct' : ActorMethod<
    [number, string, string, number, string, boolean, [] | [number]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];