/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat32;
export const ProductId = IDL.Nat32;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat32,
  'price' : IDL.Float64,
});
export const OrderId = IDL.Nat32;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : IDL.Opt(CategoryId),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Float64,
});
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [OrderId],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(CategoryId),
      ],
      [ProductId],
      [],
    ),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductCatalog' : IDL.Func(
      [],
      [
        IDL.Record({
          'categories' : IDL.Vec(Category),
          'products' : IDL.Vec(Product),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listAllProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(CategoryId),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat32;
  const ProductId = IDL.Nat32;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat32,
    'price' : IDL.Float64,
  });
  const OrderId = IDL.Nat32;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : IDL.Opt(CategoryId),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [OrderId],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(CategoryId),
        ],
        [ProductId],
        [],
      ),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductCatalog' : IDL.Func(
        [],
        [
          IDL.Record({
            'categories' : IDL.Vec(Category),
            'products' : IDL.Vec(Product),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listAllProductsSortedByPrice' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(CategoryId),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };