/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : CategoryId, 'name' : string }
export type CategoryId = number;
export interface Order {
  'id' : number,
  'customerName' : string,
  'customerAddress' : string,
  'totalAmount' : number,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : number,
  'price' : number,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : [] | [CategoryId],
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'price' : number,
}
export type ProductId = number;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminSeedInitialProducts' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], CategoryId>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, number, string, string, string],
    number
  >,
  'createProduct' : ActorMethod<
    [string, string, number, string, boolean, [] | [CategoryId]],
    ProductId
  >,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[number], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductCatalog' : ActorMethod<
    [],
    { 'categories' : Array<Category>, 'products' : Array<Product> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllCategories' : ActorMethod<[], Array<Category>>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listAllProductsSortedByPrice' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, string], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, number, string, boolean, [] | [CategoryId]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];