/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat32,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat32,
  'customerName' : IDL.Text,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GoogleReviewConfig = IDL.Record({
  'fallbackRating' : IDL.Text,
  'placeId' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Float64,
});
export const MenuCategory = IDL.Record({
  'name' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});
export const SwitchCategory = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
});
export const SwitchProduct = IDL.Record({
  'id' : IDL.Nat32,
  'categoryId' : IDL.Opt(IDL.Nat32),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductCategoryResponse = IDL.Record({
  'categories' : IDL.Vec(SwitchCategory),
  'products' : IDL.Vec(SwitchProduct),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminSeedMenuItems' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat32],
      [],
    ),
  'createSwitchCategory' : IDL.Func([IDL.Text], [IDL.Nat32], []),
  'createSwitchProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool, IDL.Opt(IDL.Nat32)],
      [IDL.Nat32],
      [],
    ),
  'deleteSwitchCategory' : IDL.Func([IDL.Nat32], [], []),
  'deleteSwitchProduct' : IDL.Func([IDL.Nat32], [], []),
  'fetchGoogleRating' : IDL.Func(
      [],
      [
        IDL.Record({
          'fallbackMessage' : IDL.Text,
          'rating' : IDL.Opt(IDL.Float64),
          'reviewCount' : IDL.Opt(IDL.Nat),
        }),
      ],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoogleReviewConfig' : IDL.Func(
      [],
      [IDL.Opt(GoogleReviewConfig)],
      ['query'],
    ),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat32], [IDL.Opt(Order)], ['query']),
  'getSwitchCatalog' : IDL.Func([], [ProductCategoryResponse], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateGoogleReviewConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSwitchCategory' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
  'updateSwitchProduct' : IDL.Func(
      [
        IDL.Nat32,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Nat32),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat32,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat32,
    'customerName' : IDL.Text,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GoogleReviewConfig = IDL.Record({
    'fallbackRating' : IDL.Text,
    'placeId' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MenuCategory = IDL.Record({
    'name' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  const SwitchCategory = IDL.Record({ 'id' : IDL.Nat32, 'name' : IDL.Text });
  const SwitchProduct = IDL.Record({
    'id' : IDL.Nat32,
    'categoryId' : IDL.Opt(IDL.Nat32),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductCategoryResponse = IDL.Record({
    'categories' : IDL.Vec(SwitchCategory),
    'products' : IDL.Vec(SwitchProduct),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminSeedMenuItems' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'createSwitchCategory' : IDL.Func([IDL.Text], [IDL.Nat32], []),
    'createSwitchProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Nat32),
        ],
        [IDL.Nat32],
        [],
      ),
    'deleteSwitchCategory' : IDL.Func([IDL.Nat32], [], []),
    'deleteSwitchProduct' : IDL.Func([IDL.Nat32], [], []),
    'fetchGoogleRating' : IDL.Func(
        [],
        [
          IDL.Record({
            'fallbackMessage' : IDL.Text,
            'rating' : IDL.Opt(IDL.Float64),
            'reviewCount' : IDL.Opt(IDL.Nat),
          }),
        ],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoogleReviewConfig' : IDL.Func(
        [],
        [IDL.Opt(GoogleReviewConfig)],
        ['query'],
      ),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat32], [IDL.Opt(Order)], ['query']),
    'getSwitchCatalog' : IDL.Func([], [ProductCategoryResponse], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateGoogleReviewConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSwitchCategory' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
    'updateSwitchProduct' : IDL.Func(
        [
          IDL.Nat32,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Nat32),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };